README.md

The badges provide a prominent indication of the repository's CI status at a glance. This may help to bring potential
issues to the attention of the maintainers.

Add badges to readme for all CI workflows

---

.github/workflows/sync-labels.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/sync-labels.yml
workflow-templates/sync-labels.yml

Because I have noticed both `.yml` and `.yaml` in use in Arduino tooling projects, I decided to add in support for both in the templates. This was done as a bit of an afterthought and not tested well. The expected failure of the label sync workflow while it was hosted in the staging repository masked the unexpected failure caused by these bugs.

Fix file patterns used to match both YAML file extensions in label sync template

---

workflow-templates/check-python-task.md

This is the latest version, which we have already updating to using in several projects, including this one (https://github.com/arduino/tooling-project-assets/pull/104), with no problems.

Update "Check Python" template's pep8-naming dependency to ^0.12.0

---

workflow-templates/test-go-integration-task.md

The template requires the installation of the `poetry:install-deps` task, but this "asset" was not mentioned in the
installation instructions.

Add missing asset to docs for "Test Integration" workflow (Go, Task) template

---

workflow-templates/check-python-task.md

This is the latest version, which we have already updating to using in several projects, including this one (https://github.com/arduino/tooling-project-assets/pull/108), with no problems.

Update "Check Python" template's black dependency to ^21.7b0

---

workflow-templates/assets/release-go-task/DistTasks.yml
workflow-templates/assets/release-go-task/Taskfile.yml
workflow-templates/release-go-task.md

* Use public variables for injected values in version package
* Update DistTasks to the latest version that supports golang 1.16+
* Some nitpiack updates to docs in release-go-task.md file

Updates to release go task

---

workflow-templates/assets/cobra/docsgen/go.mod
workflow-templates/check-go-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-go-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-integration-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
workflow-templates/test-go-integration-task.yml
workflow-templates/test-go-task.yml

We are now using Go 1.16 in the release and nightly templates (https://github.com/arduino/tooling-project-assets/pull/110), I think it makes sense to use the same version for testing, linting, and command line documentation generation.

Use Go 1.16 in all templates

---

workflow-templates/deploy-mkdocs-versioned-poetry.md

Since we are using GitPython 3.1.19 when testing the versioning helper script used by this template  (https://github.com/arduino/tooling-project-assets/pull/112), it seems best to specify that as the minimum version.

Bump GitPython dependency of "Deploy Website" workflow (versioned, MkDocs, Poetry) template

---

workflow-templates/check-yaml-task.md

The update makes a fix to the tool's package metadata which is not directly relevant to its functionality, but is essential to preserve compatibility with Poetry.
We are already using the new version in this project's own infrastructure (https://github.com/arduino/tooling-project-assets/pull/116).

Update "Check YAML" template's yamllint dependency to ^1.26.2

---

.editorconfig
workflow-templates/assets/general/.editorconfig

[The `.gitmodules` file](https://git-scm.com/docs/gitmodules) defines the properties of a repository's submodules. The file automatically generated by Git submodule commands use tabs for indentation.
It uses the same file format as [the Git configuration file](https://git-scm.com/docs/git-config#_configuration_file) (e.g., `.gitconfig`). Even though the `.gitconfig` file is not likely to be found under the repository tree, it's possible the `.editorconfig` might end up being used outside the project specific scope so I added it to the file pattern.

Add Git configuration files to template `.editorconfig`

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/publish-go-tester-task.yml
workflow-templates/publish-go-tester-task.yml

Tester builds are intended to facilitate pull request review and beta testing. For the sake of efficiency, the paths
filter should be configured to skip tester build generation on changes that have no effect on the binary, but also so
that they are always generated on any modification to a relevant file. Since the `DistTasks.yml` file is used to build
the application, it is very much relevant.

Generate tester builds on the modification of any relevant file

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/publish-go-tester-task.yml
workflow-templates/publish-go-tester-task.yml

Previously, the workflow name value was used as a component of the "PACKAGE_NAME_PREFIX" used to add identifying information to the version output and file names of tester builds. That happened to work when used with the "test" name
of [the source workflow](https://github.com/arduino/arduino-cli/blob/e31a717ebc34fff80892dbbe25a9d4581906e13a/.github/workflows/test.yaml). However, due to a lack of quoting in the build commands, once the tester build operation was moved to a dedicated workflow with a more descriptive name, it broke the build.
Example:
```
task: [dist:Windows_32bit] docker run -v `pwd`/..:/home/build -w /home/build \
-e CGO_ENABLED=1 \
docker.elastic.co/beats-dev/golang-crossbuild:1.16.4-main \
--build-cmd "go build -o dist/arduino-lint_windows_386/arduino-lint.exe -ldflags ' …
```

Fix invalid tester build version prefix

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-integration-task.yml
workflow-templates/test-go-integration-task.yml

Bugs can sometimes be operating system-specific, so it's important to test with all of them. This was done in[ the source
workflow](https://github.com/arduino/arduino-cli/blob/e31a717ebc34fff80892dbbe25a9d4581906e13a/.github/workflows/test.yaml), but ended up being lost when the  integration testing functionality was moved to a dedicated workflow.

Run Go integration tests on all operating systems

---

.github/workflows/check-yaml-task.yml
.github/workflows/spell-check-task.yml
workflow-templates/check-mkdocs-task.yml
workflow-templates/check-yaml-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-mkdocs-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-yaml-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/deploy-mkdocs-poetry.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/deploy-mkdocs-versioned-poetry.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/spell-check-task.yml
workflow-templates/deploy-cobra-mkdocs-versioned-poetry.yml
workflow-templates/deploy-mkdocs-poetry.yml
workflow-templates/deploy-mkdocs-versioned-poetry.yml
workflow-templates/spell-check-task.yml

Placement of this information at the top of the file, where it is easy to find and edit, facilitates updates to the workflows as the tool version used for project development are bumped periodically.
This is an established convention in the "template" workflows, but I missed some applications of it. I think it's most effective when done consistently throughout the workflows.

Use workflow variables for tool versions in all workflows

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
workflow-templates/test-go-task.md
workflow-templates/test-go-task.yml

This will record the project's test coverage data on Codecov, as was done in [the source workflow](https://github.com/arduino/arduino-cli/blob/e31a717ebc34fff80892dbbe25a9d4581906e13a/.github/workflows/test.yaml), but somehow didn't make it into the template.
Markup is provided for badges that will display the % coverage and link to the project's data (e.g., [![Codecov](https://codecov.io/gh/arduino/arduino-lint/graph/badge.svg)](https://codecov.io/gh/arduino/arduino-lint)).

Add Codecov upload step to "Test Go" workflow

---

workflow-templates/assets/check-go-task/Taskfile.yml
workflow-templates/check-go-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-go-task.yml

The update from Go 1.14 to 1.16 broke the task that runs golint. The good news is that[ the new `go install` command ](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies)eliminates the need for the workaround of running the `go get golang.org/x/lint/golint` command from outside the project path to avoid polluting go.mod/go.sum.
The bad news is the `go list` command used to get the path of the golint installation does not work in the "module-aware
mode" that is now the default (and will be the only as of Go 1.17):
```
missing go.sum entry for module providing package golang.org/x/lint/golint; to add:
go mod download golang.org/x/lint
task: Command "go list -f {{".Target}}" golang.org/x/lint/golint" failed: exit status 1
```
In the end, I gave up on making the task …

Make go:lint task compatible with Go 1.16

---

workflow-templates/assets/go-task/Taskfile.yml
workflow-templates/assets/test-go-task/Taskfile.yml
workflow-templates/check-go-task.md
workflow-templates/test-go-task.md

The tasks used by "Check Go" and "Test Go" workflows use the `DEFAULT_GO_PACKAGES` taskfile variable, which provides a list of all the repository's Go packages. The variable was previously located in the "test-go-task" assets, and so implicitly covered by the "Test Go" workflow's installation instructions. However, it was not present in the assets for the "Check Go" workflow.
The solution is to move this shared asset to the general purpose "go-task" assets and add instructions to both workflows' docs for the installation of that asset.

Add missing install docs for "Check Go" asset

---

workflow-templates/check-go-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-go-task.yml

The `check-config` job of the "Check Go" workflow runs a check to see whether there were any missed updates to the `go.mod` and `go.sum` files. Previously, only a single module was supported. But a project might have multiple modules, as is the case with any project that uses the Cobra command line reference generation system.
The use of a job matrix will allow the workflow to accommodate any number of modules a project may contain, at any location.

Add support for multiple modules to "Check Go" workflow

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
workflow-templates/release-go-task.yml

The `create-release` job of the "Release" workflow creates a GitHub release and uploads the built binaries as release assets. Since the binaries come from the workflow artifact, there is no need for this job to checkout the repository. The pre-release identification step uses [the `GITHUB_REF` environment variable defined by GitHub Actions](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables), which is not dependent on the runner having a repository checked out.
This means the checkout step serves no purpose. Since it makes the workflow less efficient and more difficult to maintain, it must be removed.
---
Demonstration workflow run with this change: https://github.com/per1234/arduino-lint/runs/3276843334
The resulting release: …

Remove superfluous checkout step from "Release" workflow

---

workflow-templates/assets/deploy-cobra-mkdocs-versioned-poetry/Taskfile.yml

The tasks under [the `deps` key](https://taskfile.dev/#/usage?id=task-dependencies) run in parallel, which is not appropriate for the task that is intended to format the output from the documentation generation tasks. The generation tasks will typically be able to run concurrently, so the `go:cli-docs` task can stay in `deps`, but the formatting task must be[ placed in `cmds`](https://taskfile.dev/#/usage?id=calling-another-task), which will cause it to run after
all tasks in `deps` have finished.

Run formatting task after documentation generation

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
workflow-templates/release-go-task.yml

The subfolders that remain in the Go release system's build output cause a bunch of warnings in the workflow run summary and logs resulting from the step that uploads the archives as release assets:
```
Warning: Artifact is a directory:dist/serial-discovery_0.0.42_Linux_32bit/. Directories can not be uploaded to a release.
Warning: Artifact is a directory:dist/serial-discovery_0.0.42_Linux_64bit/. Directories can not be uploaded to a release.
Warning: Artifact is a directory:dist/serial-discovery_0.0.42_Linux_ARM64/. Directories can not be uploaded to a release.
Warning: Artifact is a directory:dist/serial-discovery_0.0.42_Linux_ARMv6/. Directories can not be uploaded to a release.
Warning: Artifact is a directory:dist/serial-discovery_0.0.42_Linux_ARMv7/. Directories can not be uploaded …
```

Add explanatory comment re: release asset upload warning

---

workflow-templates/assets/cobra/docsgen/go.mod

I reviewed [the changes since v1.1.1](https://github.com/spf13/cobra/compare/v1.1.1...v1.2.1) and [tested it in Arduino Lint](https://github.com/arduino/arduino-lint/pull/253) and found it to be OK.

Bump `github.com/spf13/cobra` command docs generation dependency to v1.2.1

---

workflow-templates/deploy-mkdocs-poetry.md

A copy/paste error resulted in the wrong workflow filename being referenced in the configuration instructions.

Fix typo in template workflow documentation

---

workflow-templates/check-python-task.md

I have evaluated the changes since 0.12.0 and found nothing to be concerned about. We have already updated to this version in several projects, including in this repository's own infrastructure (https://github.com/arduino/tooling-project-assets/pull/129).

Bump "Check Python" template's `pep8-naming` dependency

---

workflow-templates/deploy-mkdocs-poetry.md

I have reviewed the changes and found nothing of concern.
This is the version now in use for the Arduino Lint website without problems: https://github.com/arduino/arduino-lint/pull/256
"dev" deployment using `mkdocs-material@7.2.4`:
- https://github.com/arduino/arduino-lint/actions/runs/1123035833
- https://arduino.github.io/arduino-lint/dev/
Test release deployment in my fork using  `mkdocs-material@7.2.4`:
- https://github.com/per1234/arduino-lint/actions/runs/1123028041
- https://per1234.github.io/arduino-lint/1.3/

Bump `mkdocs-material` website dependency to ^7.2.4

---

workflow-templates/deploy-cobra-mkdocs-versioned-poetry.md
workflow-templates/deploy-mkdocs-versioned-poetry.md

The "siteversion" Python script used by the versioned website templates is installed to
`docs/siteversion/siteversion.py`.
The configuration instructions for this script previously omitted the `docs` part of that path, which might cause
confusion.

Specify full path to helper script in versioned website docs

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
workflow-templates/test-go-task.md
workflow-templates/test-go-task.yml

The "Test Go" workflow uploads code coverage data to Codecov. There will occasionally be spurious upload failures caused by transient network outages. These will typically succeed after the workflow is re-run, but the option to re-run is not offered when the workflow run passes.
Because it's important that the data be complete, [the `codecov/codecov-action` action](https://github.com/codecov/codecov-action) is configured to fail the workflow run if the upload does not succeed. However, the upload will never be able to succeed for workflow runs in a fork where the owner has not set up Codecov. For this reason, [the `fail_ci_if_error` input](https://github.com/codecov/codecov-action#arguments) setting is made conditional upon [the repository …

Don't require Codecov upload success for test run in fork

---

.ecrc
Taskfile.yml
workflow-templates/assets/check-general-formatting/.ecrc

The `Exclude` array in [the `.ecrc` configuration file](https://github.com/editorconfig-checker/editorconfig-checker#configuration) contains the regular expressions of paths that should be excluded from checking by the editorconfig-checker tool.
Previously, the "template" file contained a list of filenames that should always be ignored. Although it worked, it was not really correct because the `.` in the filename is actually a regex wildcard, which is not what was intended. Although a false match was unlikely, this also might mislead users adding project-specific exclusions to the file regarding the nature of the exclude patterns. Changing to very explicit patterns avoids any chance of false matches and also makes it clear that these are regexes.

Make editorconfig-checker exclude regexes explicit

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/publish-go-nightly-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
workflow-templates/publish-go-nightly-task.yml
workflow-templates/release-go-task.yml

Some complex and lengthy commands are used to repackage the macOS build of the Go application after notarization. Adding
some escaped line breaks and indenting the line continuations to indicate the command structure makes it easier to read
and understand.
This was already done for the other complex commands of the workflows, but was neglected for the repackaging step.

Improve readability of macOS repackaging commands

---

workflow-templates/assets/check-go-task/Taskfile.yml
workflow-templates/assets/go-task/Taskfile.yml
workflow-templates/assets/test-go-task/Taskfile.yml
workflow-templates/check-go-task.md
workflow-templates/test-go-task.md

Although support was added to the Go module related "templates" for projects which contain modules at other paths (https://github.com/arduino/tooling-project-assets/pull/136), the assumption remained that there will always be a primary module in the root of the repository, and this path was hardcoded at several locations in the taskfiles.
It might be that a project that is not a Go module contains an accessory Go module in a subfolder ([example](https://github.com/arduino/library-registry/tree/production/.github/workflows/assets/validate-registry)). In this case, the use
of a taskfile variable will allow that path to be defined in one place, avoiding the need to override the hardcoded incorrect location whenever a Go module-related task is run manually.

Use taskfile variable to define primary Go module path

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/publish-go-tester-task.yml
workflow-templates/publish-go-tester-task.yml

The default behavior of [the `actions/checkout` action](https://github.com/actions/checkout) is to do a shallow fetch of the repository, which is the most efficient if all that's needed is a copy of the repository files. In cases where the repository history is needed, this behavior is not appropriate, and so it can be configured via the `fetch-depth` input. [Setting this input to 0](https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches) causes the full history to be fetched.
A full fetch is required for workflows that use [the `arduino/create-changelog` action](https://github.com/arduino/create-changelog) to generate a raw changelog from the commit history, and so it is found in the "Release" workflow. However, there is no use of the commit history by the …

Use shallow fetch for Go tester build

---

Taskfile.yml
workflow-templates/assets/check-go-task/Taskfile.yml
workflow-templates/assets/check-markdown-task/Taskfile.yml
workflow-templates/assets/check-python-task/Taskfile.yml
workflow-templates/assets/check-shell-task/Taskfile.yml

I originally set out to establish some logical order to the tasks in the taskfiles I've worked in. Based from the start
on some indecipherable and subjective criteria, then randomized to some extent by the whims of Git over the course of
development, it ends up a jumble.
Alphabetical order is completely objective and it results in a fairly logical order in the end due to the practice of
using prefixes on the task names according to their domain. The exception I make is placing the convenience "umbrella"
tasks at the top (in their own alphabetical order) so that they will have the maximum visibility as the most useful tasks.
Even that is not completely inconsistent, since these don't have a namespace prefix, and so might be imagined to have a
null global namespace prefix that should be …

Sort tasks in alphabetical order

---

workflow-templates/assets/check-go-task/Taskfile.yml

There is an established practice of providing the developer with convenience "umbrella" tasks which collect multiple
tasks of a given type of operation. This has a couple of benefits:
- Provides an alternative to manually running multiple tasks
- Provides a standardized interface to the project, independent from its unique underlying details
However, I have come to the conclusion that these benefits lessen as the number of such convenience tasks increases. At
the same time, the maintenance burden increases. In the end, my preference is to have only the "umbrella" convenience
tasks at the highest possible level, which seems to be:
- "build" (build the application)
- "check" (check for problems with the project)
- "fix" (automatically fix problems with the project)
The decision about …

Remove superfluous `go:check` template task

---

.codespellrc
workflow-templates/assets/spell-check/.codespellrc

The `ignore-words-list` and `skip` settings of [the codespell configuration file](https://github.com/codespell-project/codespell#using-a-config-file) may required project-specific adjustments to fix false positives or avoid positives from externally maintained files. The other settings are universal. It will be convenient to have the settings the user might need to adjust at the place of highest visibility in the configuration file.

Place project-specific settings first in codespell configuration

---

workflow-templates/assets/cobra/docsgen/main.go
workflow-templates/deploy-cobra-mkdocs-versioned-poetry.md

I identified some project-specific aspects of the template "docsgen" program for generating the website Cobra CLI reference content. These are resolved, mitigated, or documented by this pull request.
See the individual commits for details:
https://github.com/arduino/tooling-project-assets/pull/144/commits

Improve "docsgen" program's usability as a "template"

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
workflow-templates/test-go-task.yml

In order to catch platform-specific bugs, the "Test Go" workflow uses a job matrix to run the tests on multiple runners. The step that uploads code coverage data to Codecov is intended to run only during the Linux job. The runner name `ubuntu-latest` was used in the conditional to accomplish this. However, I'm observing that sometimes it is necessary or desirable to pin a specific runner version (e.g., `ubuntu-18.04`). The accompanying adjustment to the conditional might be forgotten and there would not be any obvious sign that the coverage upload had stopped, not why.
So I'm thinking the better approach would be to use the general [`runner.os` context item](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#runner-context) to identify the Linux …

Avoid workflow conditional reliance on specific runner

---

.github/workflows/test-python-poetry-task.yml
workflow-templates/check-go-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-go-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/publish-go-tester-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-integration-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-python-poetry-task.yml
workflow-templates/publish-go-tester-task.yml
workflow-templates/test-go-integration-task.yml
workflow-templates/test-go-task.yml
workflow-templates/test-python-poetry-task.yml

This is a sync of a downstream improvement which has been reviewed and approved: https://github.com/arduino/arduino-cli/pull/1400
---
The [trunk-based development](https://trunkbaseddevelopment.com/) strategy is used by some tooling projects (e.g., Arduino CLI). Their release branches may contain a subset of the history of the default branch.
The status of the GitHub Actions workflows should be evaluated before making a release. However, this is not so simple as checking the status of the commit at the tip of the release branch. The reason is that, for the sake of efficiency, the [workflows are configured](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on) to run only when the processes are relevant to the trigger event (e.g., no need to run unit tests for …

Run relevant workflows on release branch creation

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-tag.yml
workflow-templates/release-tag.md
workflow-templates/release-tag.yml

The requirement emerged (https://github.com/arduino/pluggable-discovery-protocol-handler/pull/12) for a release workflow that can be applied to projects that don't have any release assets to build and upload.
On every push of a release tag (e.g., `1.2.3` or `v1.2.3`) to the repository, create a [GitHub release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/about-releases) with a raw [changelog generated](https://github.com/arduino/create-changelog) from the commit history since the last release tag.
Tags that contain a [pre-release version](https://semver.org/#spec-item-9) will cause the GitHub release to be marked as a pre-release.
This workflow is especially well suited for use as a "template", since it does not have any project specific …

Add minimal GitHub release creation template workflow

---

workflow-templates/check-yaml-task.md

There was a new patch release of the tool and we are updating to using this as the standard version for all tooling
projects, including already in use by this project (https://github.com/arduino/tooling-project-assets/pull/150).

Bump "Check YAML" template's `yamllint` dependency

---

workflow-templates/check-python-task.md

This is now the standard version of the `black` Python code formatter tool for use in Arduino tooling projects.
It is already in use in multiple project, including this one: https://github.com/arduino/tooling-project-assets/pull/154

Bump `black` dependency to `^21.8b0`

---

workflow-templates/test-go-integration-task.md
workflow-templates/test-python-poetry-task.md

This is now the standard version of the `pytest` Python testing framework for use in Arduino tooling projects.
It is already in use in multiple projects, including this one: https://github.com/arduino/tooling-project-assets/pull/156

Bump `pytest` dependency to ^6.2.5 in templates

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
workflow-templates/release-go-task.yml

A file containing a list of checksums for the build archives is generated by the system used by the "Release Go"
template. The macOS build archive is modified later in the process as a result of the repackaging following notarization.
For this reason, the checksum file must be updated. The `sha256sum` command used to generate the original file separates
the checksum from the filename with two spaces. Previously, the command that updates the macOS checksum only added a
single space, which caused the formatting of the file to be inconsistent:
```
d5dccece4253b8c4c7e86b80f77433b3f3363ee89dcf11fd91d4638bbc66b61e  bhy_0.0.1_Linux_32bit.tar.gz
15557602d6aa6fd0a64b88393b7bd06fde35d6855a51c6b6a56a89ebd7d55153  bhy_0.0.1_Linux_64bit.tar.gz …
```

Align macOS filename with others in checksum file

---

workflow-templates/deploy-mkdocs-poetry.md
workflow-templates/deploy-mkdocs-versioned-poetry.md

New releases have arrived of the `mkdocs-material` dependency of all our MkDocs-based websites, and the `mike` dependency
of the versioned website. These are already in use by the Arduino Lint website (https://github.com/arduino/arduino-lint/pull/269, https://github.com/arduino/arduino-lint/pull/268).

Bump dependencies for website templates

---

workflow-templates/deploy-mkdocs-versioned-poetry.md

This is now the standard version of the `gitpython` Python package for use in the website versioning helper script.
It is already in use in Arduino Lint (https://github.com/arduino/arduino-lint/pull/271) and this repository's own CI system (https://github.com/arduino/tooling-project-assets/pull/161).
Release notes: https://github.com/gitpython-developers/GitPython/blob/main/doc/source/changes.rst#3123

Bump `gitpython` dependency to ^3.1.23 in template

---

workflow-templates/deploy-mkdocs-versioned-poetry.md

This is now the standard version of the `mike` Python package used for versioning of MkDocs websites, already in use in Arduino Lint (https://github.com/arduino/arduino-lint/pull/273).

Bump `mike` dependency to ^1.1.1 in template

---

workflow-templates/check-python-task.md

This is now the standard version of the `black` Python package used for formatting Python code. This version is already in use in this repository's own infrastructure (https://github.com/arduino/tooling-project-assets/pull/164).

Bump `black` dependency to ^21.9b0 in template

---

workflow-templates/assets/sync-labels/tooling.yml

Two new labels are added to the shared repository label configuration file for tooling projects. These will allow the
current stage in the development work to resolve an issue to be indicated.
At the moment, the phases recognized by the tooling team are design and implementation. Additional labels will be added
if more distinct phases emerge in practice.
These labels will be added to all repositories that use the "Sync Labels" workflow with the tooling.yml shared label configuration on the next run (scheduled daily).

Add shared phase labels for tooling projects

---

other/installation-script/installation.md

This document is intended to provide a list of installation options:
- script
- download
- build
but the heading levels were misaligned, which resulted in this structure:
- script
- download
- build
Example of the bug in production:
https://arduino.github.io/arduino-lint/dev/installation/

Align heading levels in template install docs

---

other/installation-script/installation.md

This repository hosts a reusable "template" installation instructions document, which is currently in use by Arduino CLI and Arduino Lint.
User feedback about the first time Arduino CLI installation experience revealed some opportunities to make minor improvements to this content, which are proposed here.

Make template install instructions more user friendly

---

other/installation-script/installation.md

A reference link provides easy access to the relevant information for readers who are not familiar with this concept
while not harming readability for everyone else by increasing verbosity.
This had already been done for the script method installation instructions (https://github.com/arduino/tooling-project-assets/commit/7894fd751127a2d09d46b9f43b950068224c6d05), but not for the direct download method
instructions. Since the user is only intended to read the instructions for the specific installation method they choose,
the reference link must be added to the first mention of `PATH` in each set of instructions.

Add missing reference link re: `PATH` to template install docs

---

other/installation-script/installation.md

A placeholder "PRODUCT_NAME" is used when referring to the specific software product in the "template" installation
instructions document. As is explained in the associated readme, these placeholders are replaced when the "template" is
applied to a repository to tailor it to that specific project.
The document previously used a more ambiguous "this tool" at one location when referring to the product. That sentence
will be more clear to the reader if the specific product name is used there, and so it is replaced by the placeholder.

Use placeholder for product in template install docs

---

workflow-templates/check-python-task.md

These will now be the standard versions Python code tool for use in Arduino tooling projects:
- [flake8](https://flake8.pycqa.org/en/latest/)@^4.0.1
- [black](https://github.com/psf/black)@^21.10b0

Bump Python code tools used in "templates"

---

workflow-templates/check-python-task.md

This is now the standard version of the `black` Python code formatting tool for use in Arduino tooling projects.

Bump `black` dependency to ^21.11b1 in template

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-integration-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
workflow-templates/test-go-integration-task.yml
workflow-templates/test-go-task.yml

The recent 3.9.1 release of [the Task task runner](https://taskfile.dev/#/) does not correctly handle the `PATH` environment variable on Windows.
Since the "template" workflows were configured to always use the latest version of Task within the 3.x major version
series, this bug caused spurious failure of workflows under the following conditions:
- Used a Windows runner
- Ran a task that contained a command reliant on a file from PATH
([example](https://github.com/arduino/arduino-cli/runs/4355349975?check_suite_focus=true#step:6:546))
The workaround is to pin the version of Task used in these workflows to the last working version: 3.9.0.

Pin Windows-compatible version of Task where necessary

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-integration-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
workflow-templates/test-go-integration-task.yml
workflow-templates/test-go-task.yml

This reverts commit 8d6e59fa716b8800e1fe3b99d606c2ab8f72bce0.
A new 3.9.2 release of Task is out with a fix for the the Windows PATH handling bug that affected 3.9.1 (https://github.com/mvdan/sh/issues/768). So it is no longer necessary to do a full pin of Task in the "Template" workflows.
Pinning only the major version series allows the workflows to use the latest version of Task until such time as a breaking change necessitates a major version bump. This provides the right balance of access to beneficial developments, while requiring manual review in the event that development might break something.

Revert "Pin Windows-compatible version of Task where necessary"

---

.github/workflows/check-taskfiles.yml
.github/workflows/sync-labels.yml
workflow-templates/check-taskfiles.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-taskfiles.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-tag.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/sync-labels.yml
workflow-templates/release-tag.yml
workflow-templates/sync-labels.yml

The [`carlosperate/download-file-action` action](https://github.com/carlosperate/download-file-action) is used in the GitHub Actions workflows as a convenient way to download external resources.
A [major version ref](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management) has been added to that repository:
https://github.com/carlosperate/download-file-action/releases/tag/v1
It will always point to the latest release of the "1" major version series.
This means it is no longer necessary to do a full pin of the action version in use as before.
Use of the major version ref will cause the workflow to use a stable version of the action, while also benefiting from ongoing development to the action up until such time as a new major release of an …

Use major version ref of `carlosperate/download-file-action`

---

.github/workflows/test-install-script.yml
other/installation-script/install.sh

The "template" installation script stored in this repository checks for an existing installation in the `PATH` in order to provide appropriate advice to the user about adding the installation to their their `PATH` environment variable.
This check is done using `command -v`. It turns out that the exit status is shell dependent in the event the command is not found, so that it might be either `1` or `127` depending on the user's system. The script previously assumed that the exit status would be `1` when the command was not found in `PATH`, which resulted in spurious advice under these conditions:
https://github.com/arduino/tooling-project-assets/runs/4556007479?check_suite_focus=true#step:4:13
```
An existing arduino-lint was found at . Please prepend …
```

Fix install script's check for previous installation

---

workflow-templates/check-python-task.md
workflow-templates/deploy-mkdocs-poetry.md
workflow-templates/deploy-mkdocs-versioned-poetry.md

These dependencies of the "templates" are now the standard versions for use in Arduino tooling projects.
They are already in use in Arduino Lint and in this repository's own CI system:
- https://github.com/arduino/tooling-project-assets/pull/187
- https://github.com/arduino/tooling-project-assets/pull/193
- https://github.com/arduino/arduino-lint/pull/319

Bump dependencies in templates

---

workflow-templates/deploy-mkdocs-versioned-poetry.md

This is now the standard version of the `gitpython` Python module for use in Arduino tooling projects.
It is already in use in this repository's CI system as well as other Tooling projects:
- https://github.com/arduino/tooling-project-assets/pull/195
- https://github.com/arduino/arduino-lint/pull/320
- https://github.com/arduino/compile-sketches/pull/44

Bump `gitpython` dependency to ^3.1.26 in template

---

workflow-templates/assets/sync-labels/arduino-tooling-gh-label-configuration-schema.json
workflow-templates/assets/sync-labels/tooling.yml
workflow-templates/assets/sync-labels/universal.yml

At the time the original configuration file was developed, it was in JSON, which does not support comments. I found the need to add some internal explanatory commentary to some of the labels, so I added an arbitrary `notes` key as a container for this information, and our JSON schema was also configured to accept this field.
I later decided to convert the files to YAML, since that is the language used by the majority of the asset configuration files. At this point it became possible to use comments, but the `notes` field was already in place so it seemed pointless to change it.
Validation of the configuration file [was added](https://github.com/Financial-Times/github-label-sync/pull/158) to the "**GitHub Label Sync**" tool in [the recent 2.1.0 …

Remove `notes` from allowed properties in label configuration schema

---

workflow-templates/assets/sync-labels/universal.yml

The "Sync Labels" template workflow uses a "universal" label configuration file hosted in this repository, which defines the GitHub labels that are used in all Arduino tooling project repositories.
The "**topic: infrastructure**" label is applied to all issues and PRs related to the project infrastructure (as opposed to the content of the project itself or its documentation). This "infrastructure" includes the dependencies, which are normally managed by Dependabot.
By default, Dependabot applies a label named "**dependencies**" to its PRs. This is configurable, but experience shows that is often forgotten. With the previous configuration, the "**topic: infrastructure**" label must be manually applied to the Dependabot PRs. The "**dependencies**" label is added here as an "alias" for …

Improve configuration for "topic: infrastructure" shared label

---

workflow-templates/check-go-dependencies-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-go-dependencies-task.yml

The "**Check Go Dependencies**" GitHub Actions workflow checks for dependencies with incompatible or unapproved license types.
The dependency license metadata consumed by [the "**Licensed**" tool](https://github.com/github/licensed) is cached in the project repository, in a dedicated file for each dependency.
The `check-cache` job of the workflow checks whether that cache is in sync with the project's current dependencies. It does this by using the "Licensed" tool to update the cache and then a [`git diff`](https://git-scm.com/docs/git-diff) command to check whether that resulted in any changes (which would indicate it is out of sync).
Out of sync states could result from any of three distinct conditions:
- Missing metadata file
- Incorrect metadata file contents
- Superfluous metadata …

Detect unused dependency license metadata files

---

other/installation-script/install.sh

The "template" installation script contained a `get()` function used to make an HTTP request.
The response body is required by the caller, but shell functions do not support returning content as you might do when using a more capable programming language.
As a workaround, the script author set up a system where the caller passed an arbitrary variable name to the function, which the function then assigns with the response body string.
This was done using [the `eval` builtin](https://man7.org/linux/man-pages/man1/eval.1p.html). The `eval` command was quoted in a naive manner, not considering that the body content could contain any arbitrary characters. This made it possible that contents of the response body could be unintentionally executed on the user's machine.
In the context of the …

Remove broken frivolous function from install script

---

other/installation-script/install.sh

Apple's [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)) allows applications built for x86-64 hosts to run on machines using their ARM 64-bit M1 processor.
Due to current infrastructure challenges (e.g., lack of GitHub-hosted GitHub Actions runners), Arduino's applications may not yet be available as native M1 builds, yet the existing macOS x86-64 builds work perfectly well on these machines thanks to Rosetta 2.
The installation script previously failed to install these applications when ran on the M1 host (https://github.com/arduino/tooling-project-assets/issues/207):
```text
Did not find a release for your system: macOS arm64
```
---
In order to facilitate review, I'll attach a copy of the version of the "template" script from this PR which has been configured to install …

Fallback to x86-64 release when macOS ARM 64-bit build not available

---

.github/workflows/check-dependabot.yml
.github/workflows/check-labels.yml
.github/workflows/check-markdownlint.yml
README.md
Taskfile.yml

Previously, the validation of various configuration files stored and/or used in the repository was done by a single monolithic task and workflow. Due to the different characteristics of the files and their JSON schemas, there was no real benefit from this approach in terms of efficiency or maintainability.
As validation of additional configuration file types became necessary, the previous system grew more unwieldy. Splitting it up into separate tasks and workflows offers several primary benefits:
- Tasks are more maintainable
- CI workflows are more efficient due to only running validations relevant to the specific configuration files that were modified

Split configuration file validation infrastructure by type

---

Taskfile.yml

An error in the JSON schema for the markdownlint configuration file required the use of the corrected (https://github.com/DavidAnson/markdownlint/pull/406) schema file from the development branch temporarily.
The fix has now reached the production branch, so the workaround can be reverted:
https://github.com/DavidAnson/markdownlint/blob/main/schema/build-config-schema.js#L35

Return to using production version of markdownlint schema

---

issue-templates/minimal/README.md
issue-templates/template-choosers/README.md
issue-templates/template-choosers/general/README.md
issue-templates/template-choosers/general/config.yml
issue-templates/template-choosers/github-actions/README.md
issue-templates/template-choosers/github-actions/config.yml

A collection of reusable [GitHub issue template chooser configuration files](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) are stored in this repository.
Previously, their documentation was located in the documentation for the [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). The reasoning for that approach was that the template chooser feature is exclusive to repositories that have issue templates. However, it does not scale well as additional issue templates are added, and also makes it difficult to find information about these template …

Move docs for issue template chooser configs alongside assets

---

.github/workflows/check-issue-templates.yml
README.md
Taskfile.yml
issue-templates/forms/README.md
issue-templates/forms/general/README.md
issue-templates/forms/general/bug-report.yml
issue-templates/forms/general/feature-request.yml
issue-templates/forms/platform-dependent/README.md
issue-templates/forms/platform-dependent/bug-report.yml
issue-templates/forms/platform-dependent/feature-request.yml

High quality feedback via GitHub issues is a very valuable contribution to the project. It is important to make the issue creation and management process as efficient as possible for the contributors, maintainers, and developers.
Issue templates are helpful to the maintainers and developers because it establishes a standardized framework for the issues and encourages the contributors to provide the essential information.
When a repository is configured to use the GitHub issue forms system, the contributor is now presented with a [a web form](https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) when creating an issue. This consists of multi-line input fields that have the same …

Add a collection of reusable issue form configuration files

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-crosscompile-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
workflow-templates/release-go-crosscompile-task.yml
workflow-templates/release-go-task.yml

Followup of f3291c6e4c706be12cc0ad5096b88f85298ee282
This problem causes the "Identify Prerelease" step to not correctly detect a prerelease:
`/home/runner/work/_temp/86a34b5f-71b2-4554-ba4c-b3d565415455.sh: line 3: /tmp/semver: Permission denied`
Example run: https://github.com/arduino/imgtool-packing/runs/6455908108?check_suite_focus=true#step:5:14

fix semver-tool version. 3.2.0 is downloaded but 3.0.0 is still used.

---

.markdown-link-check.json
workflow-templates/assets/check-markdown/.markdown-link-check.json

The link check job of the "Check Markdown" workflow has had frequent intermittent spurious failures recently, caused by links under the `docs.github.com` domain returning [403 HTTP status](https://en.wikipedia.org/wiki/HTTP_403).
Others experiencing the same problem reported that they were able to work around the problem by providing a custom [`Accept-Encoding` HTTP request header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) (e.g, https://github.com/tcort/markdown-link-check/issues/201#issuecomment-1110242146). Although I was not able to find any explanation of why, it does appear to resolve the problem.
Since the problem seems to be permanent and the only other workarounds I have identified are unappealing (considering links returning 403 statuses alive, or …

Configure link check to use `Accept-Encoding` header for docs.github.com links

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/publish-go-nightly-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-crosscompile-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
workflow-templates/publish-go-nightly-task.yml
workflow-templates/release-go-crosscompile-task.yml
workflow-templates/release-go-task.yml

The workflow is using v3 now, and there has not been any on the permissions situation documented by this comment:
https://github.com/actions/upload-artifact/tree/v3#permission-loss
Since we have gotten behind on this comment at each bump and there is no sign that they will ever change the behavior (and also no reason to believe that it would align with a major version bump even if they did), I think it is best to just remove the version specification from the comment altogether.

Remove outdated action version specification from comments

---

.github/workflows/check-python-task.yml
.github/workflows/check-yaml-task.yml
.github/workflows/spell-check-task.yml
.github/workflows/test-python-poetry-task.yml
workflow-templates/check-go-dependencies-task.yml
workflow-templates/check-go-task.yml
workflow-templates/check-mkdocs-task.yml
workflow-templates/check-python-task.yml
workflow-templates/check-yaml-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-go-dependencies-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-go-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-mkdocs-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-python-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-yaml-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/deploy-mkdocs-poetry.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/deploy-mkdocs-versioned-poetry.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-crosscompile-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/spell-check-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-integration-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-python-poetry-task.yml
workflow-templates/deploy-cobra-mkdocs-versioned-poetry.yml
workflow-templates/deploy-mkdocs-poetry.yml
workflow-templates/deploy-mkdocs-versioned-poetry.yml
workflow-templates/release-go-crosscompile-task.yml
workflow-templates/spell-check-task.yml
workflow-templates/test-go-integration-task.yml
workflow-templates/test-go-task.yml
workflow-templates/test-python-poetry-task.yml

GitHub Actions actions are used by the workflows to set up development tools in the runner workspace.
In order to facilitate updates to new versions of these tools, we specify the tool version to be set up via [environment variables](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env) at the top of the workflow.
Since this variable definition is separate from the step using the action, it might not be immediately apparent to the maintainer which version syntaxes are supported. For this reason, comments were added with the URL to the relevant section of the consuming action's documentation. Previously, these URLs were made to point to the version of the documentation that matched the version of the action in use by the workflow. Since we only use a …

Use non-version specific reference URLs for tool version workflow variables

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/test-go-task.yml
workflow-templates/test-go-task.yml

For the sake of efficiency, the "Test Go" GitHub Actions workflow is [configured](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) to run only when relevant files are modified. Since the workflow uploads code coverage data to [Codecov](https://about.codecov.io/), the Codecov configuration file is one of these files.
The standard filename for the Codecov configuration file is `codecov.yml`, and the workflow's path filter was configured for that filename. It turns out an alternative filename is also recognized: `.codecov.yml`. Two subfolders are also supported in addition to the root of the repository as locations for the configuration file. …

Add support to "Test Go" workflow for alternative Codecov configuration paths

---

.github/workflows/check-npm-task.yml
Taskfile.yml
workflow-templates/assets/check-npm-task/Taskfile.yml
workflow-templates/assets/check-workflows-task/Taskfile.yml
workflow-templates/assets/windows-task/Taskfile.yml
workflow-templates/check-npm-task.md
workflow-templates/check-npm-task.yml
workflow-templates/check-workflows-task.md
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-npm-task.yml

The [Task task runner tool](https://taskfile.dev/) uses [an integrated Bash shell interpreter](https://github.com/mvdan/sh) to allow the use of standard POSIX/Bash syntax and built-in utilities while providing cross-platform support for users who have made the poor choice of the non-standard Windows cmd or PowerShell shells.
While this is a nice feature of Task, distinguishing it from other alternatives, it is still often necessary to use non-built-in utilities.So use of a Bash shell is a requirement to run our tasks even the developers using Windows.
Although high quality Bash shells for Windows such as the Git Bash included as part of the [Git for Windows](https://git-scm.com/download/win) installation generally provide a seamless experience, there is the occasional "gotcha".
Relative …

Convert absolute paths used in tasks to Windows format

---

Taskfile.yml
workflow-templates/assets/check-npm-task/Taskfile.yml
workflow-templates/assets/windows-task/Taskfile.yml

The [**ajv-cli** command line tool](https://github.com/ajv-validator/ajv-cli) is used for validating data files against their [JSON schema](https://json-schema.org/).
In general, it is preferable (for some schemas even mandatory) to use the modern versions of **ajv-cli**. However, support for the ["Draft 4" schema specification](https://json-schema.org/specification-links.html#draft-4) was dropped in [**avj** version 7.0.0](https://github.com/ajv-validator/ajv/releases/tag/v7.0.0), [introduced into **ajv-cli**](https://github.com/ajv-validator/ajv-cli/commit/5d2939ece4273b4306f43d4efef59f3033768168) at version 4.0.0. So when working with JSON schemas that specify that draft, it is necessary to use **ajv-cli** 3.3.0, the last compatible version.
This means that some projects may have …

Force use of unmanaged ajv-cli version as required

---

.github/workflows/check-clang-format.yml
Taskfile.yml
other/clang-format-configuration/.clang-format
other/clang-format-configuration/notes.md
other/clang-format-configuration/testdata/golden/samples/arduino-libraries/Arduino_MKRMEM/examples/SPIFFSDirectories/SPIFFSDirectories.ino
other/clang-format-configuration/testdata/golden/samples/arduino-libraries/EducationShield/examples/Block2-Sports/Projects/Pong/Pong.ino
other/clang-format-configuration/testdata/golden/samples/arduino-libraries/EducationShield/examples/Block4-Robots/Projects/CameraRobot/CameraRobot.ino
other/clang-format-configuration/testdata/golden/samples/arduino/ArduinoCore-samd/libraries/SBU/examples/SBU_LoadLZSS/lzssEncode.cpp
other/clang-format-configuration/testdata/golden/samples/arduino/ArduinoCore-samd/libraries/USBHost/examples/USB_desc/USB_desc.ino
other/clang-format-configuration/testdata/golden/targeted/AllowShortIfStatementsOnASingleLine.cpp
other/clang-format-configuration/testdata/golden/targeted/EmptyLineAfterAccessModifier.cpp
other/clang-format-configuration/testdata/golden/targeted/EmptyLineBeforeAccessModifier.cpp
other/clang-format-configuration/testdata/golden/targeted/IndentRequires.cpp
other/clang-format-configuration/testdata/golden/targeted/PackConstructorInitializers.cpp
other/clang-format-configuration/testdata/golden/targeted/SpacesInAngles.cpp
other/clang-format-configuration/testdata/golden/targeted/Standard.cpp
other/clang-format-configuration/testdata/input/targeted/AllowShortIfStatementsOnASingleLine.cpp
other/clang-format-configuration/testdata/input/targeted/IndentRequires.cpp
other/clang-format-configuration/testdata/input/targeted/PackConstructorInitializers.cpp

The **ClangFormat** configuration file hosted in this repository was developed for use with [**ClangFormat** 11.0.1](https://releases.llvm.org/11.0.1/tools/clang/docs/ClangFormat.html). The version of ClangFormat now in use by the Arduino IDE 2.x is 14.0.0:
https://github.com/arduino/arduino-ide/blob/19c0334a91cf562cf63edf0496eae16165499f8f/arduino-ide-extension/package.json#L164-L166
Configuration keys were added, removed, or changed in type in the interim.
The configuration file and its maintenance infrastructure are hereby updated for use with [**ClangFormat** 14.0.0](https://releases.llvm.org/14.0.0/tools/clang/docs/ClangFormat.html).
The goal is always be to preserve consistent formatter output through any changes that must be made to the file. Since Arduino IDE 2.x is still in a …

Update ClangFormat configuration file for ClangFormat 14.0.0

---

workflow-templates/assets/check-action-metadata-task/Taskfile.yml
workflow-templates/check-action-metadata-task.md
workflow-templates/check-action-metadata-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-action-metadata-task.yml

On every push or pull request that affects the [`action.yml`](https://docs.github.com/actions/creating-actions/metadata-syntax-for-github-actions) GitHub Actions metadata file, and periodically, validate `action.yml` against [its JSON schema](https://json.schemastore.org/github-action.json).
These assets have been in use for the last 1.5 years in the `arduino/setup-task` repository (https://github.com/arduino/setup-task/pull/2). They are submitted here for hosting in a centralized location to facilitate their maintenance and use in the the Arduino Tooling Team's other GitHub Actions actions projects.
Minor fixes and enhancements have been added to the initial import to bring the assets up to the current state of the art (see the individual commit messages for details).

Add template for validating GitHub Actions action metadata

---

workflow-templates/assets/release-go-task/DistTasks.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/publish-go-nightly-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/publish-go-tester-task.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
workflow-templates/publish-go-nightly-task.yml
workflow-templates/publish-go-tester-task.md
workflow-templates/publish-go-tester-task.yml
workflow-templates/release-go-task.yml

Updates:
- `release-go-task`, `publish-go-nigthly-task` and `publish-go-tester-task` now use a matrix to run build tasks simultaneously instead of running them sequencially with `dist:all`. This also allows to directly upload a different artifact for each build in `publish-go-tester-task`.
- Checksums are calculated in the release creation job only.
- `DistTasks` no longer has a `dist:all` task.
This changes were originally introduced with PR [1883](https://github.com/arduino/arduino-cli/pull/1883) in the [arduino-cli](https://github.com/arduino/arduino-cli) repository.

Update release workflows using parallelization

---

workflow-templates/dependabot/workflow-template-copies/.github/workflows/release-go-task.yml
workflow-templates/release-go-task.yml

The **"Release" workflow (Go, Task, CGO)** template was recently changed to use a job matrix to run builds for each target in parallel. The new design is intended to use a dedicated task for each target instead of the previous approach of executing a single `dist:all` task.
The task name was not updated at that time, which caused the workflow to fail:
```text
task: Task "dist:all" not found
```
The task invocation is hereby updated to use the target-specific task names.

Use correct task name to build project in release workflow

---

.github/workflows/check-taskfiles.yml
Taskfile.yml
workflow-templates/assets/check-npm-task/Taskfile.yml
workflow-templates/check-taskfiles.yml
workflow-templates/dependabot/workflow-template-copies/.github/workflows/check-taskfiles.yml

In order to avoid duplication of content, JSON schemas may reference other schemas via the `$ref` keyword. The [ajv schema validator](https://github.com/ajv-validator/ajv-cli) tool used by the asset does not automatically follow external references. For this reason, the addition of external references to the schemas used results in a spurious validation failure:
https://github.com/arduino/tooling-project-assets/actions/runs/3367815680/jobs/5585665098#step:5:74
```text
schema /home/runner/work/_temp/json-schema/package-json-schema.json is invalid
error: can't resolve reference https://json.schemastore.org/npm-badges.json from id #
```
https://github.com/arduino/tooling-project-assets/actions/runs/3367828391/jobs/5585693418#step:6:17
```text
schema …
```

Fix schema validation failures resulting from added references

---

workflow-templates/check-certificates.yml

The "Check Certificates" GitHub Actions workflow uses [**OpenSSL**](https://www.openssl.org/) to check for problems with the project's signing certificates.
Certificates exported to [PKS #12](https://en.wikipedia.org/wiki/PKCS_12) archive files using older tools may have been encrypted using the ["RC2-40-CBC" algorithm](https://en.wikipedia.org/wiki/RC2).
Due to the availability of more secure modern alternatives, [default support for RC2-40-CBC encryption was dropped in **OpenSSL** 3.x](https://www.openssl.org/docs/man3.0/man7/migration_guide.html#PKCS-12-API-updates).
The macOS signing certificate currently used by Arduino uses this "RC2-40-CBC" encryption so it will be best to configure the workflow to still support this algorithm.
The "Check Certificates" GitHub Actions workflow runs …

Use OpenSSL "legacy" provider in "Check Certificates" for compatibility w/ RC2-40-CBC encrypted PKS#12

---

.github/workflows/check-general-formatting-task.yml
.github/workflows/check-javascript-task.yml
.github/workflows/check-npm-task.yml
.github/workflows/check-prettier-formatting-task.yml
.github/workflows/check-taskfiles.yml
.github/workflows/spell-check-task.yml
workflow-templates/check-action-metadata-task.yml
workflow-templates/check-general-formatting-task.yml
workflow-templates/check-javascript-task.yml
workflow-templates/check-npm-task.yml
workflow-templates/check-prettier-formatting-task.yml
workflow-templates/check-taskfiles.yml
workflow-templates/check-toc-task.yml
workflow-templates/spell-check-task.yml

This is a continuation of previous work to provide pre-release validation for projects using the "[trunk-based development](https://trunkbaseddevelopment.com/)" strategy: https://github.com/arduino/tooling-project-assets/pull/148. The workflows previously adapted in this way have been 
---
The [trunk-based development](https://trunkbaseddevelopment.com/) strategy is used by some tooling projects (e.g., Arduino CLI). Their release branches may contain a subset of the history of the default branch.
The status of the GitHub Actions workflows should be evaluated before making a release. However, this is not so simple as checking the status of the commit at the tip of the release branch. The reason is that, for the sake of efficiency, the [workflows are …

Expand workflow support for "trunk-based development" strategy

---

.github/workflows/check-shell-task.yml
.github/workflows/test-install-script.yml
Taskfile.yml
workflow-templates/assets/check-dependencies-task/Taskfile.yml
workflow-templates/assets/check-general-formatting-task/Taskfile.yml
workflow-templates/assets/check-markdown-task/Taskfile.yml
workflow-templates/assets/check-shell-task/Taskfile.yml
workflow-templates/assets/go-task/Taskfile.yml
workflow-templates/check-shell-task.yml
workflow-templates/deploy-cobra-mkdocs-versioned-poetry.yml
workflow-templates/deploy-mkdocs-versioned-poetry.yml
workflow-templates/publish-go-nightly-task.yml
workflow-templates/release-go-crosscompile-task.yml
workflow-templates/release-go-task.yml
workflow-templates/release-tag.yml

[120 columns](https://github.com/arduino/tooling-project-assets/blob/3ebb02742786e76d3f51d7d6e48fe80af6c01c73/workflow-templates/assets/check-yaml/.yamllint.yml#L36) is the [recommended](https://github.com/arduino/tooling-project-assets/blob/3ebb02742786e76d3f51d7d6e48fe80af6c01c73/workflow-templates/assets/check-yaml/.yamllint.yml#L35) line length for YAML code in Arduino tooling projects. The [**yamllint**](https://github.com/adrienverge/yamllint) tool used by [the "Check YAML" template](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-yaml-task.md) produces a warning when a line exceeds this length.
This is not a hard limit and in some cases it is either impossible or not beneficial to make lines less than 120 in length so some violations of the …

Reduce line length to <=120 in YAML files where feasible

---

workflow-templates/assets/check-dependencies-task/Taskfile.yml
workflow-templates/assets/check-go-dependencies-task/Taskfile.yml
workflow-templates/assets/check-npm-dependencies-task/Taskfile.yml
workflow-templates/check-go-dependencies-task.md

The "Check npm Dependencies" template is used to check for compatibility of dependencies with the licensing of projects that use [**npm**](https://www.npmjs.com/) for dependency management.
The [**Licensed**](https://github.com/github/licensed) tool is used for this check. This tool requires the dependencies to have been installed in advance.
Previously, the template's task did not install the dependencies. This caused the check to fail whenever the dependencies were not already installed by chance.
The dependency check tasks are intended to be applicable to projects of any type since the **Licensed** tool [supports multiple project types (referred to as "sources")](https://github.com/github/licensed/blob/master/docs/sources). Each project type might have different requirements for …

Install npm dependencies in "Check npm Dependencies" template

---

workflow-templates/check-go-dependencies-task.yml
workflow-templates/check-npm-dependencies-task.yml

The [**Licensed**](https://github.com/github/licensed) tool is used to check for a project's compatibility with the licensing of its dependencies.
This tool is installed by the "Check Go Dependencies" and "Check npm Dependencies" [GitHub Actions workflows](https://docs.github.com/actions/using-workflows/about-workflows) using [the `jonabc/setup-licensed` GitHub Actions action](https://github.com/jonabc/setup-licensed). This action attempts the installation according to the following procedure:
1. Install [the Ruby gem](https://rubygems.org/gems/licensed).
1. If gem installation fails, install the [release](https://github.com/github/licensed/releases/latest) asset from the `github/licensed` repo.
Spurious failures of the runs of these workflows are occurring due to hitting [the rate …

Configure dependency license check workflows to avoid failure of Licensed installation

---

workflow-templates/release-go-task.yml
workflow-templates/release-tag.yml

The condition to identify a prerelease was recently split to reduce the length of the line, causing the workflow to fail throwing this error:
```
/home/runner/work/_temp/1435c811-653a-480e-bcf6-c38ae8bd5d7e.sh: line 7: unexpected token `newline', conditional binary operator expected
Error: Process completed with exit code 2.
```
Adding some \ inside the condition should fix this issue.
This PR is also introducing an explicit comparison inside the test, which checks whether `semver` returns a string or not, to make the code more readable.

Fix `Identify Prerelease` step in the release worflow

---

workflow-templates/assets/release-go-crosscompile-task/DistTasks.yml
workflow-templates/release-go-crosscompile-task.yml

Introducing the use of a matrix, greatly improves time performances during the build making process, since each build task is performed simultaneously. To support this, a check has been added to avoid creating the same changelog more than once.
The calculation of the checksums has also been modified. Previously, it was done three (3) times at different stages of the workflow. This is pointless, since the only checksums that matter are the ones calculated when the files are in their final form. For this reason, it is now only done once during the release creation.
`arduino101load` [2.3.0 release](https://github.com/arduino/arduino101load/actions/runs/4182432555) was made using this workflow.

Build releases simultaneously in `release-go-crosscompile-task` workflow

---

workflow-templates/check-markdown-task.md

The dependency `markdownlint-cli` was recently [bumped](https://github.com/arduino/tooling-project-assets/pull/311) to version `0.33.0`. This PR fixes a typo introduced in `check-markdown-task`'s documentation.

Fix `markdownlint-cli` version typo in `check-markdown-task` documentation

---

workflow-templates/deploy-cobra-mkdocs-versioned-poetry.md
workflow-templates/deploy-cobra-mkdocs-versioned-poetry.yml

The **"Deploy Website" (Cobra, versioned, MkDocs, Poetry)** template is used to generate and publish a documentation website for projects based on the [**Cobra**](https://github.com/spf13/cobra) command line application framework.
Command line reference pages are generated from the project's Go codebase.
Previously, the default version of Go from the GitHub Actions runner machine was used for generating the documentation content. A recent update of this default Go version from 1.17 to 1.20 (https://github.com/actions/runner-images/issues/7276) caused the generation process to fail during the workflow runs in some projects that use older Go versions:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 …
```

Use project Go version for generating website content

---

workflow-templates/release-tag.yml

A stray quote was present in a shell command in the workflow. This caused a spurious failure of the "Identify Prerelease" step:
```
unexpected EOF while looking for matching `"'
```

Remove extra quote from shell command in release-tag workflow

---

.github/workflows/check-license.yml
workflow-templates/check-license.md
workflow-templates/check-license.yml

The `check-license.yml` workflow checks if the specified license file is present in the root directory of the repository. This PR, provides the option of checking any subdirectories as well
- 🧷 Works without regression even if additional `path:` keys are not specified
- 😄 Minimalistic: uses `cd` to enter `path:` keys and run the steps
- ⏳ All license checks are performed in the same job saving compute resources
This PR feeds back improvements upstream from https://github.com/arduino/nicla-sense-me-fw/pull/115

[AE-45] Multipath options for `check-license.yml`

---

.github/workflows/check-npm-task.yml
Taskfile.yml
workflow-templates/assets/check-npm-task/Taskfile.yml
workflow-templates/assets/npm-task/Taskfile.yml
workflow-templates/check-npm-task.md
workflow-templates/check-npm-task.yml

The assets and repository infrastructure validates various configuration file against their [JSON schema](https://json-schema.org/overview/what-is-jsonschema).
The [**ajv-cli**](https://ajv.js.org/packages/ajv-cli.html) validator is used to perform the validation. **ajv-cli** supports the use of globs in [the data file path argument](https://ajv.js.org/packages/ajv-cli.html#d-json-data). "[globstar](https://github.com/isaacs/node-glob#glob-primer:~:text=**%20If%20a%20%22globstar%22%20is%20alone%20in%20a%20path%20portion%2C%20then%20it%20matches%20zero%20or%20more%20directories%20and%20subdirectories%20searching%20for%20matches.)s" are used to cause the tool to search the file tree in the repository recursively for data files to validate.
Previously these glob patterns were not carefully …

Prevent uncontrolled file tree recursion while validating configuration files

---

Taskfile.yml

The repository infrastructure validates the project's own, as well as the "asset", [**Dependabot** configuration files](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file) against [the JSON schema](https://json.schemastore.org/dependabot-2.0). The [**ajv-cli**](https://ajv.js.org/packages/ajv-cli.html) JSON schema validator is used to perform the validation.
Support for the JSON schema ["Draft-04" specification](https://json-schema.org/specification-links#draft-4) was dropped at the [4.0.0 release of **ajv-cli**](https://github.com/ajv-validator/ajv-cli/releases/tag/v4.0.0). This means that the previous version ([3.3.0](https://github.com/ajv-validator/ajv-cli/releases/tag/v3.3.0)) …

Use modern version of validator to validate Dependabot configuration files

---

.github/workflows/check-shell-task.yml
Taskfile.yml
workflow-templates/assets/check-shell-task/Taskfile.yml
workflow-templates/check-shell-task.md
workflow-templates/check-shell-task.yml

Previously, the approach taken in the "Check Scripts" template was to recursively search the entire repository for shell scripts. There were several problems with that system:
---
The [`-regextype` flag](https://www.gnu.org/software/findutils/manual/html_node/find_html/Full-Name-Patterns.html#index-_002dregextype) used in the `find` commands of the `shell:check` and `shell:check-mode` tasks is not supported by [the BSD/macOS version of `find`](https://ss64.com/osx/find.html), meaning the tasks would fail if a contributor using a macOS machine tried to run them:
```text
find: -regextype: unknown primary or operator
```
---
The `shell:check` and `shell:check-mode` tasks only provided coverage for files with `.sh` and `.bash` file extensions, whereas the practice of omitting a file extension …

Target specific scripts in "Check Scripts" template

---

Taskfile.yml
workflow-templates/assets/check-markdown-task/Taskfile.yml

The `markdown:check-links` task uses the [**markdown-link-check**](https://github.com/tcort/markdown-link-check). This tool [does not have a capability for discovering Markdown files](https://github.com/tcort/markdown-link-check/issues/40) so it is necessary to use the [`find`](https://www.gnu.org/software/findutils/manual/html_node/find_html/Invoking-find.html) command to discover the files, then pass their paths to the **markdown-link-check** tool.
Since it is managed as a project dependency using [**npm**](https://www.npmjs.com/), the **markdown-link-check** tool is invoked using [`npx`](https://docs.npmjs.com/cli/commands/npx). Since the `find` command must be ran in combination with **markdown-link-check**, it is necessary to use the `--call` flag of `npx`. Even though Windows …

Avoid platform-specific code in `markdown:check-links` task

---

Taskfile.yml
workflow-templates/assets/check-files-task/Taskfile.yml

The ["**"Check Files" (Task)**" template](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-files-task.md) includes an asset task named `general:check-filenames` that checks for the presence of non-portable filenames in the project.
Ironically, the task itself was non-portable. The problem was that it used [the `--perl-regexp` flag](https://www.gnu.org/software/grep/manual/html_node/grep-Programs.html#index-matching-Perl_002dcompatible-regular-expressions) in the `grep` command. This flag is not supported by [the BSD version of grep](https://ss64.com/osx/grep.html) used on macOS and BSD machines. This caused the task to fail spuriously with `grep: unrecognized option '--perl-regexp'` errors when ran on a macOS or BSD machine.
The incompatibility is …

Fix macOS/BSD incompatibility in `general:check-filenames` task

---

workflow-templates/check-certificates.yml

The new windows certificate we have is no more distributed digitally, and it's not inside a certificate container anymore.
This PR adds support for a single certificate.
An implementation of this can be seen in:
- https://github.com/arduino/arduino-cli/pull/2599
- https://github.com/arduino/arduino-create-agent/pull/950

add support to x509 certificates

---

workflow-templates/check-go-dependencies-task.yml
workflow-templates/publish-go-nightly-task.yml
workflow-templates/publish-go-tester-task.yml
workflow-templates/release-go-task.yml
workflow-templates/sync-labels.yml

Updates the artifacts-related actions to the latest version:
* [actions/upload-artifact@v4](https://github.com/actions/upload-artifact)
* [actions/download-artifact@v4](https://github.com/actions/download-artifact)
* [geekyeggo/delete-artifact@v5](https://github.com/geekyeggo/delete-artifact)
Here the migration guide > https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md
This changes have been successfully used in the Arduino CLI: 
- https://github.com/arduino/arduino-cli/pull/2679
- https://github.com/arduino/arduino-cli/pull/2682

Update some workflows upload/download artifact actions

---

workflow-templates/check-go-dependencies-task.yml
workflow-templates/check-npm-dependencies-task.yml

A breaking change was made in the 3.2.1 release of the [**actions/upload-artifact**](https://github.com/actions/upload-artifact) action (https://github.com/actions/upload-artifact/issues/602), without doing a major version bump as would be done in a responsibly maintained project. The action now defaults to not uploading "hidden" files.
The "**Check Go Dependencies**" and "**Check npm Dependencies**" templates use the [**Licensed**](https://github.com/github/licensed) tool to check for incompatible dependency licenses. The dependencies license metadata cache used by **Licensed** is stored in a folder named `.licensed`.
In order to facilitate updates, the workflows of these templates upload the generated dependencies license metadata cache as a [workflow …

Configure actions/upload-artifact action to upload required hidden files

---

workflow-templates/publish-go-nightly-task.yml
workflow-templates/release-go-crosscompile-task.yml
workflow-templates/release-go-task.yml

In a previous revision of the release workflows (https://github.com/arduino/tooling-project-assets/pull/243), the updated checksums were determined by the macOS notarization job and then passed to the subsequent job via job outputs. That approach was changed during a later refactoring (https://github.com/arduino/tooling-project-assets/pull/277, https://github.com/arduino/tooling-project-assets/pull/326), but the code that declares the job outputs was not removed at that time.
The checksum job output declaration code is now unused (and unusable since the checksum determination and output definitions were removed) so it only makes the workflows more difficult to understand and maintain. For this reason, the vestigial code is hereby removed from the workflows.

Remove unused job outputs from release workflows

---

workflow-templates/check-javascript-task.md

The templates and documentation contain reference links to provide additional information to the users and maintainers.
The targets of this link has moved since the time they were added. Although the user could still reach the intended content via a redirect, it is best not to rely on redirects continuing to work indefinitely. So the URL is hereby updated to point directly to the target content.

Update redirecting URL in reference link

---

.github/workflows/sync-labels-npm.yml
workflow-templates/sync-labels-npm.yml
workflow-templates/sync-labels.yml

Starting from version 3.2.0 of the [**actions/upload-artifact**](https://github.com/actions/upload-artifact) action, "hidden" files are not uploaded by default (https://github.com/actions/upload-artifact/issues/602). The action considers a file "hidden" if any component of the path starts with `.`.
The `download` job of the "Sync Labels" workflow downloads each of the shared label configuration files from and uploads them to GitHub Actions [workflow artifacts](https://docs.github.com/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow#about-workflow-artifacts) for use by the subsequent job. Since the names of the configuration files don't start with `.` and they aren't located in a subfolder that starts with `.`, we would not expect that …

Use explicit filename source in config file artifact upload step of "Sync Labels" workflows

---

workflow-templates/publish-go-nightly-task.yml
workflow-templates/release-go-crosscompile-task.yml
workflow-templates/release-go-task.yml

The **"Release" workflow (Go, Task, Crosscompile)** template uses a GitHub Actions workflow to automatically generate releases of a project. This is done for a range of host architectures, including macOS. The macOS builds are then put through a notarization process in a dedicated workflow job.
The builds are transferred between jobs by GitHub Actions workflow artifacts. The `create-release-artifacts` job produces macOS workflow artifacts containing non-notarized builds, which must then be replaced after the builds are notarized by the `notarize-macos` job.
Previously, the approach chosen to accomplish this replacement was to use the community created **geekyeggo/delete-artifact** action to delete each artifact after it had been downloaded by the `notarize-macos` job, then replacing it by …

Use more efficient workflow artifact replacement approach

---

workflow-templates/publish-go-nightly-task.yml
workflow-templates/release-go-task.yml

These GitHub Workflows are used to automatically generate and publish production and nightly releases of a project. This is done for a range of host architectures, including macOS. The macOS builds are then put through a notarization process in a dedicated workflow job.
GitHub Actions workflow artifacts are used to transfer the generated files between sequential jobs in the workflow. The **actions/upload-artifact** and **actions/download-artifact** actions are used for this purpose.
The workflow artifact handling had to be reworked recently in order to handle a breaking change in the 4.0.0 release of the **actions/upload-artifact** action (https://github.com/arduino/tooling-project-assets/pull/507 / https://github.com/arduino/tooling-project-assets/commit/3b7926719f8e360a9649e3c5e0cd815bf8 …

Fix collision between macOS workflow artifacts in release workflows

---

workflow-templates/publish-go-nightly-task.yml
workflow-templates/release-go-task.yml

GitHub Workflows are used to automatically generate and publish production and nightly releases of the project. This is done for a range of host architectures, including macOS. The macOS builds are then put through a notarization process in a dedicated workflow job.
GitHub Actions workflow artifacts are used to transfer the generated files between sequential jobs in the workflow. The builds are transferred between jobs by GitHub Actions workflow artifacts, one for each host architecture.
Previously, the "notarize-macos" job matrix that performs the notarization unnecessarily downloaded all the build artifacts, even though each job only requires the relevant macOS artifact. This is inefficient.
The better approach is to configure the "notarize-macos" jobs to only download the artifact they …

Only download required artifact in notarization job of release workflows

---

workflow-templates/check-go-dependencies-task.yml
workflow-templates/check-npm-dependencies-task.yml

This GitHub Actions action is used by the dependency license check workflows to install the [**Licensed**](https://github.com/licensee/licensed) tool in the runner workspace.
The action has a convoluted history of ownership: the repository was originally owned by GitHub user [`jonabc`](https://github.com/jonabc). It was later transferred to the [`github`](https://github.com/github) organization. Then GitHub abandoned the project, archiving the repository. The [`licensee`](https://github.com/licensee) organization has now created a hard fork of the action, which is recommended in [the readme of the `github/setup-licensed` repository](https://github.com/github/setup-licensed#setup-licensed).
The `licensee` organization has also taken over the management of the **Licensed** tool, and their …

Use maintained fork of "setup-licensed" action in dependency license check workflow

---

workflow-templates/check-go-dependencies-task.yml
workflow-templates/check-npm-dependencies-task.yml

The version of the [**Licensed**](https://github.com/licensee/licensed) tool for use in the GitHub Actions workflow is defined via the **github/setup-licensed** action's `version` input.
Previously the action was configured to install version 3.x of the action. That version is significantly outdated. The workflow is hereby updated to use the latest version of **Licensed**.

Bump "Licensed" version in dependency license check workflow

---

.github/dependabot.yml
workflow-templates/assets/dependabot/dependabot.yml

Dependabot is used to keep the project dependencies updated. Dependabot periodically checks for available updates, and if found submits a pull request.
The frequency of the update checks is configurable. Despite the name, the "daily" schedule configuration previously used actually only runs on weekdays. Maintenance of open source software projects is not necessarily limited to weekdays (and in the case of volunteer projects, is more likely to occur on weekends). So the weekday-ly update checks tended to result in a concentration of Dependabot pull requests on Mondays. This unnecessarily added to the busyness of an already busy day.

Configure Dependabot to check for updates daily

---

Taskfile.yml
workflow-templates/assets/check-npm-task/Taskfile.yml
workflow-templates/assets/windows-task/Taskfile.yml

The [**ajv-cli** command line tool](https://github.com/ajv-validator/ajv-cli) is used for validating data files against their [JSON schema](https://json-schema.org/). The tool is used to validate the project's Dependabot, ESLint, and npm configuration files.
In general, it is preferable (and for some schemas even mandatory) to use the modern versions of **ajv-cli**. However, support for the ["Draft-04" schema specification](https://json-schema.org/specification-links.html#draft-4) was dropped in **ajv-cli** version 4.0.0. So when working with JSON schemas that specify that draft, it is necessary to use **ajv-cli** 3.3.0, the last compatible version.
Previously, the Dependabot, ESLint, and npm schemas specified the "Draft-04" specification. For this reason, the `dependabot:validate`, …

Use project version of ajv-cli in all validation tasks

---

.github/workflows/check-dependabot.yml
.github/workflows/check-issue-templates.yml
.github/workflows/check-labels.yml
.github/workflows/check-markdownlint.yml

These GitHub Actions workflows use the ajv-cli JSON schema validation tool to validate data files against their JSON schema. ajv-cli is an npm package-based tool.
A standard major version of Node.js, and thus its bundled npm should be used for all development and maintenance operations. Previously, these workflows did not explicitly configure the version of Node.js that should be used in the runner machine, so whatever version happened to be installed in the runner by default was used. That version doesn't necessarily match with the intended version, and the version could change at any moment, so this risked instability in the project infrastructure.

Use standard Node.js version in validation workflows

---

workflow-templates/check-go-dependencies-task.yml
workflow-templates/check-go-task.yml
workflow-templates/deploy-cobra-mkdocs-versioned-poetry.yml
workflow-templates/release-go-crosscompile-task.yml
workflow-templates/test-go-integration-task.yml
workflow-templates/test-go-task.yml

Go is used in the development and maintenance of the project. A standardized version of Go is used for all operations.
This version is defined in the [`go` directive](https://go.dev/ref/mod#go-mod-file-go) of the `go.mod` metadata file.
Go is installed in the GitHub Actions runner environments using the **actions/setup-go** action, which also must be configured to install the correct version of Go. Previously the version number for use by the **actions/setup-go** action was defined in each workflow. This meant that we had multiple copies of the Go version information, all of which had to be kept in sync.
Fortunately, support for using `go.mod` as the source of version information for the **actions/setup-go** action was recently added: …

Use `go.mod` as source of Go version number for workflows

---

.github/workflows/check-yaml-task.yml
.yamllint.yml
workflow-templates/assets/check-yaml/.yamllint.yml
workflow-templates/check-yaml-task.yml

Several significant files use the YAML language, but not the standard `.yml` or `.yaml` file extensions. In order to provide full coverage, "yamllint" and the paths filter of the "Check YAML" workflow must be configured with the patterns for these files.
A list of filename patterns for the YAML language is maintained in the "Linguist" project. Even though Linguist is not used by this infrastructure, the data from the Linguist source code serves as a reference from which the list of patterns was derived. In order to facilitate maintenance of the list of file patterns, comments were added to the yamllint configuration file and the "Check YAML" workflow providing a link to the reference.
In the Linguist project, the data for all programming languages is stored in a single data file, which …

Update YAML filename matching pattern reference link

---

.github/workflows/check-prettier-formatting-task.yml
.prettierignore
.prettierrc.yml
Taskfile.yml
package-lock.json
package.json
workflow-templates/assets/check-prettier-formatting/.prettierignore
workflow-templates/assets/check-prettier-formatting/toml/.prettierrc.yml
workflow-templates/check-prettier-formatting-task.md
workflow-templates/check-prettier-formatting-task.yml

Projects may use data files written in the [TOML](https://toml.io/) language. A common example of such is the [`pyproject.toml`](https://packaging.python.org/en/latest/specifications/pyproject-toml/) file present in projects that use the [**Poetry**](https://python-poetry.org/) Python package management tool (either for project code dependencies, or development tools).
In cases where the TOML content is edited directly by human contributors, it will be useful to provide code formatting infrastructure for TOML files, and to enforce consistent formatting. This is easily accomplished by adding TOML support to the existing code formatting infrastructure via the **prettier-plugin-toml** plugin for the **Prettier** formatting tool.
**Poetry**'s `poetry.lock` file is also written in the TOML …

Add reference link comment for Prettier filename matching patterns

---

.github/dependabot.yml
workflow-templates/assets/check-dependencies-task/Taskfile.yml
workflow-templates/assets/check-dependencies/AGPL-3.0/.licensed.yml
workflow-templates/assets/check-dependencies/AGPL-3.0/README.md
workflow-templates/assets/check-dependencies/Apache-2.0/.licensed.yml
workflow-templates/assets/check-dependencies/Apache-2.0/README.md
workflow-templates/assets/check-dependencies/GPL-2.0/.licensed.yml
workflow-templates/assets/check-dependencies/GPL-2.0/README.md
workflow-templates/assets/check-dependencies/GPL-3.0/.licensed.yml
workflow-templates/assets/check-dependencies/GPL-3.0/README.md
workflow-templates/assets/check-dependencies/LGPL-2.1/.licensed.yml
workflow-templates/assets/check-dependencies/LGPL-2.1/README.md
workflow-templates/assets/check-dependencies/README.md
workflow-templates/assets/dependabot/dependabot.yml
workflow-templates/check-go-dependencies-task.md
workflow-templates/check-npm-dependencies-task.md

The documentation contains links to relevant information. Some of that information has been moved to a different location on the Internet since the time the comments were added.
The URLs are hereby updated to point to the current location of that content.

Update reference links in documentation

---

Taskfile.yml
workflow-templates/assets/check-go-task/Taskfile.yml
workflow-templates/assets/check-npm-task/Taskfile.yml
workflow-templates/assets/check-shell-task/Taskfile.yml
workflow-templates/assets/check-toc-task/Taskfile.yml
workflow-templates/assets/check-yaml-task/Taskfile.yml
workflow-templates/assets/npm-task/Taskfile.yml
workflow-templates/assets/windows-task/Taskfile.yml

Some tasks accept input via environment variables. It is important to document these parameter variables.
Previously, the parameter environment variables of these tasks were undocumented.
Typically, the documentation is done in the task description, to make the information easily accessible to contributors via the `task list` output. However, this approach was intentionally eschewed in the case of the `yaml:lint` task, where the documentation was instead placed in a comment. The reason is that this task's parameter variable is only useful when the task is executed by a GitHub Actions workflow, as is done already in the "Check YAML" workflow. So the contributor running the task from the command line has no need for this information and thus including it in the description would only …

Document task environment variable parameters

---

Taskfile.yml
workflow-templates/assets/check-action-metadata-task/Taskfile.yml
workflow-templates/assets/check-markdown-task/Taskfile.yml
workflow-templates/assets/check-npm-task/Taskfile.yml
workflow-templates/assets/check-prettier-formatting-task/Taskfile.yml
workflow-templates/assets/check-toc-task/Taskfile.yml
workflow-templates/assets/check-workflows-task/Taskfile.yml
workflow-templates/assets/npm-task/Taskfile.yml
workflow-templates/assets/test-go-task/Taskfile.yml

A repository might contain multiple npm-managed projects. For this reason, the appropriate npm-managed tasks have a parameter environment variable that allows it to be configured for an arbitrary path, with the "Check npm" workflow having a job matrix of paths to pass.
Generally, even if there are multiple npm-managed projects, there will be one primary project that is most often the target of contributor operation. Since it would be inconvenient for the contributor to pass the environment variable path every time they want to run a task for that primary project, the tasks are configured to have a default path which is used if the variable is not defined by the user.
Since the primary npm-managed project would typically be in the root of the repository, the default value is set to the …

Make default npm project path configurable via taskfile variable

---

workflow-templates/check-action-metadata-task.md
workflow-templates/check-files-task.md
workflow-templates/check-general-formatting-task.md
workflow-templates/check-go-dependencies-task.md
workflow-templates/check-go-dependencies-task.yml
workflow-templates/check-go-task.md
workflow-templates/check-javascript-task.md
workflow-templates/check-markdown-task.md
workflow-templates/check-npm-task.md
workflow-templates/check-poetry-task.md
workflow-templates/check-prettier-formatting-task.md
workflow-templates/check-shell-task.md
workflow-templates/check-taskfiles.md
workflow-templates/check-toc-task.md
workflow-templates/check-workflows-task.md
workflow-templates/check-yaml-task.md
workflow-templates/spell-check-task.md
workflow-templates/test-go-task.md

In order to facilitate asset installation, the installation instructions include precomposed commit and pull request messages, which can be copy and pasted by the installer.
The primordial origin of this repository was a collection of reusable GitHub Actions workflows for use in the repositories of Arduino libraries. In those projects, it is not common to make provisions for running the checks locally. For this reason, the precomposed messages in the original installation instructions focused exclusively on the GitHub Actions workflow. The installation instructions in this repository inherited that same focus. However, that approach makes less sense in this context where the primary assets are typically general purpose infrastructure, which may be used locally by the contributor in …

Improve precomposed asset installation commit and PR messages

---

workflow-templates/deploy-cobra-mkdocs-versioned-poetry.yml
workflow-templates/deploy-mkdocs-poetry.yml
workflow-templates/deploy-mkdocs-versioned-poetry.yml

The "Poetry" tool is used to manage the Python package dependencies of the website deployment workflows.
Dependencies might be classified into distinct categories. The most basic classification would be:
- Application dependencies: used by the project's applications
- Development dependencies: tools used in the development and maintenance of the project, but not by the application
By default, Poetry installs all non-optional dependencies. This can be inefficient in a case where a specific operation is being performed, since a given operation might only require the dependencies from one category and so the installation of dependencies from the other is pointless for that operation.
For this reason, Poetry allows the user to organize dependencies into arbitrary "groups", and to specify …

Only install Python package dependencies from relevant group

---

workflow-templates/assets/deploy-cobra-mkdocs-versioned-poetry/Taskfile.yml
workflow-templates/assets/test-go-task/Taskfile.yml

This will facilitate the maintenance of the assets by making it easy for the maintainers of downstream projects to find the canonical source of the variables, whether to pull upstream changes, or push changes back upstream.

Add source comments to asset task variables

---

Taskfile.yml
workflow-templates/assets/poetry-task/Taskfile.yml

This task updates all the project's Python package dependencies to the latest version.
Performing bulk updates is not a good practice, since it is non-atomic and thus makes it difficult to bisect regressions caused by the update. In addition, it is not necessary since dependencies are now updated using Dependabot.
For these reasons, the task is harmful and superfluous.

Remove `poetry:update-deps` task

---

.github/workflows/check-shell-task.yml
workflow-templates/check-shell-task.yml

The "liskin/gh-problem-matcher-wrap" action is used in the "Check Shell" workflow to enhance the workflow run results summary by applying a "problem matcher" to the output of the shellcheck tool.
This action is a wrapper around shell commands, so we would expect its `run` input to work the same as the `jobs.<job_id>.steps[*].run` key of the GitHub Actions workflow. However, this is not the case. The commands specified via the `jobs.<job_id>.steps[*].run` key can be split into multiple lines using the standard shell line continuation operator. That is useful in the case of long/complex shell commands such as the one used to execute the `shell:check` task in this workflow step. This is not possible when using "liskin/gh-problem-matcher-wrap".
A comment is added to explain this behavior.

Add comment to workflow re: unexpected behavior of "liskin/gh-problem-matcher-wrap" action

---

pyproject.toml
workflow-templates/assets/poetry/README.md
workflow-templates/assets/poetry/pyproject.toml

The `build-system` section of the `pyproject.toml` Python project file provides information about the build system used by a Python project.
The assets use Python-based tool dependencies, and `pyproject.toml` is used to define those dependencies. This is applicable to projects of any type. For projects which do not have a Python codebase, the `build-system` section is completely irrelevant. So the section should not be included in the assets. It can be added as needed in project that do have a Python codebase.

Remove superfluous `build-system` section from Python project file

---

workflow-templates/publish-go-nightly-task.yml
workflow-templates/release-go-crosscompile-task.yml
workflow-templates/release-go-task.yml

The release workflows for Go-based projects use a matrix job to perform the build for each target host architecture. The matrix data is defined by a mapping.
When a job name is not explicitly defined in the workflow GitHub Actions automatically generates the job name from the job ID and the matrix data. In cases where there is no matrix, or when the matrix data is a simple sequence of strings, that job name is often adequate. However, when the matrix data is more complex, the automatically generated name becomes overly verbose and cryptic (e.g., "create-nightly-artifacts (macOS_ARM64, macOS_ARM64, ubuntu-24.04-arm)"), harming the readability of the logs. In this case, an explicit human-friendly job name should be defined in the workflow.

Explicitly define names for build jobs in Go release workflows
